### ISSUE TITLE
New feature idea: scenario based simulation

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-simulator#140]
New feature idea from the discussion with @everpeace @shioshiota @ordovicia @superbrothers.

The current simulator doesn't have the feature allowing users to write some scenarios.

We would like to propose the feature "fake clock" and support scenario based simulation. 
Users can write their scenario on the time of  fake clock. And the scheduler and the simulator will work on that clock.
This will be useful for who wants to evaluate the scheduler with some specific scenarios.

## What can users do on the scenario

Users can create/update/delete resources supported by simulator. And they will write scenario with the time of fake clock. 
The scenarios may be written like the following, I guess:

```yaml
- time: 1
  operations:
  - op: apply
    kind: Pod
    name: pod1
    templatePath: /path/to/pod-template.yaml
  - op: create
    kind: Node
    name: node1
    templatePath: /path/to/node-template.yaml
- time: 2
  operations:
  - op: apply
    kind: Pod
    name: pod1
    templatePath: /path/to/pod-update-template.yaml
  - op: delete
     kind: Node
     name: node1
```

## What is fake clock

Fake clock is literally showing fake time.

## Why is fake clock needed

If we use the real time for scenario(e.g. create a  Pod, then 10 seconds later, create a Node.), users who have a long scenario need to wait that time.
The scheduler does not change schedule results even after a long time unless the state of other resources changes.
The state of all resources in the simulator will not change unless the user requests a change. So, even if a user has a one-week scenario, it does not mean that he/she cannot simulate that workload without actually spending a week.
Once the scheduler has tried to schedule all the pods present, we can proceed to the next resource changes defined by users.

## technical details

We need to prevent the scheduler to schedule new Pods to make simulate results stable. The scheduler must not schedule the next pod until it has completed all defined changes at the same time on the fake clock. 

The scheduler has NextPod field and this allows us to change how to fetch a next schedule target Pod and we can prevent the scheduler from scheduling Pods by using that.

/kind feature
/assign
