### ISSUE TITLE
Use API with script instead of frontend

### ISSUE THREAD

**Issue by JulianTS** [kubernetes-sigs/kube-scheduler-simulator#192]
Hey,

The simulator already helped me a bunch to develop and test custom plugins!!

I discovered the address and port of the server in the documentation but wondered if I can control everything with an extern script via the API instead of the frontend? 
Could not find the endpoints for scheduling/deleting pods and retrieving the scores yet which would be important.

Thanks in advance!!

Currently writing my BA about building and evaluating a custom plugin.
I planned to simulate cloud traces for the evaluation so that the measured impact of the plugin is more realistic, but I can't "run" them on a cluster afaik, so the simulator-server would be a great help!

Edit: doc answered a part of my question

**Comment by sanposhiho** [comment]
Hello.

The kube-apiserver inside of simulator can be accessed from outside of the simulator. That means you can use kubectl or client-go (or another k8s clients) to create/edit/delete any resource in simulator.

> Could not find the endpoints for scheduling/deleting pods and retrieving the scores yet which would be important.

- To delete Pod, you can use any k8s client as described above.
- To schedule Pods, you only need to create Pods. (Scheduler automatically find the non-scheduled Pods and try to schedule them)
- To retrieve scheduling results, you can check the Pod annotation
  - Yes, we surely need to create the function for this. The issue is https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/109

**Comment by sanposhiho** [comment]
Probably like this?

```
apiVersion: v1
kind: Config

clusters:
- cluster:
    server: http://localhost:3131
  name: simulator

contexts:
- context:
    cluster: simulator
  name: simulator

current-context: simulator
```
