### ISSUE TITLE
preemption: not eligible due to a terminating pod on the nominated node

### ISSUE THREAD

**Issue by choyuansu** [kubernetes-sigs/kube-scheduler-simulator#271]
I'm trying out a scenario to see how preemption works in Kubernetes, but I'm unable to successfully preempt a low priority pod.

## Steps to reproduce

1. Create priority class `high-priority`
    ```yaml
    metadata:
      name: high-priority
    value: 1000000
    globalDefault: false
    ```
2. Create new node
    ```yaml
    metadata:
      generateName: node-
      labels: {}
    spec: {}
    status:
      capacity:
        cpu: '4'
        memory: 32Gi
        pods: '110'
      allocatable:
        cpu: '4'
        memory: 32Gi
        pods: '110'
      phase: Running
      conditions:
        - type: Ready
          status: 'True'
    ```
3. Create low priority pod that uses all resources in the node
    ```yaml
    # low priority pod
    metadata:
      generateName: pod-
      namespace: default
      labels: {}
    spec:
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.5
          resources:
            limits:
              cpu: 4
              memory: 32Gi
            requests:
              cpu: 4
              memory: 32Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      enableServiceLinks: true
    ```
4. Create high priority pod with default resources requests and limits
    ```yaml
    # high priority pod
    metadata:
      generateName: pod-
      namespace: default
      labels: {}
    spec:
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.5
          resources:
            limits:
              cpu: 100m
              memory: 16Gi
            requests:
              cpu: 100m
              memory: 16Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      enableServiceLinks: true
      # make pod high priority
      priorityClassName: high-priority
    ```

## Expected behavior
The low priority pod is preempted and then removed from the node. The high priority pod is scheduled to the node.

## Actual behavior
The low priority pod stayed on the node. The high priority pod is in "Unscheduled Pods". In the status of the high priority pod is the message: "preemption: not eligible due to a terminating pod on the nominated node."
```yaml
# high priority pod's status
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-02-27T22:17:26Z'
      reason: Unschedulable
      message: >-
        0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory.
        preemption: not eligible due to a terminating pod on the nominated node.
```
At first, the message was only "0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory." But after a while, it added "preemption: not eligible due to a terminating pod on the nominated node."

The phase of the low priority pod is "pending" and not "terminating" as the message above claims.
```yaml
# low priority pod's status
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-02-27T22:16:31Z'
  qosClass: Guaranteed
```

![image](https://user-images.githubusercontent.com/17804434/221702667-94d870d4-3000-47c8-a5ff-40251a45ae66.png)
