### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by yueyueaa** [kubernetes-sigs/kube-scheduler-simulator#325]
```
! simulator-frontend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                       0.0s 
 ! simulator-etcd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                           0.0s 
 ! simulator-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
```
I am using a macbook air m1 chip and running the project with the above issue
My host platform is linux/arm64/v8 but the container image is built for linux/amd64. 
Due to the platform mismatch, Docker cannot run the container directly. Is there any recommended solution for this? 
Thank you!
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/84655209/81e1bd9d-3b51-4d23-99be-31c6e4b11e3a)

**Comment by sanposhiho** [comment]
@yueyueaa Ah, maybe we have to change how we build the image.
For now, you can build the image yourself with `make docker_build_and_up`.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/Makefile#L49-L50

**Comment by yueyueaa** [comment]
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/84655209/da78483f-13a0-4839-96c1-6d58e30f4452)
It seems that it didn't solve the problem by rebuilding the image.

**Comment by yueyueaa** [comment]
> @yueyueaa Ah, maybe we have to change how we build the image. For now, you can build the image yourself with `make docker_build_and_up`. https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/Makefile#L49-L50
![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/84655209/18857efd-b3c9-4841-9600-bbd9fc304239)

It seems that it didn't solve the problem by rebuilding the image.

**Comment by yueyueaa** [comment]
```
docker logs simulator-etcd
```

![image](https://github.com/kubernetes-sigs/kube-scheduler-simulator/assets/84655209/3ea2efd6-5a61-46ab-9e24-b73af3144d5d)

**Comment by sanposhiho** [comment]
It's weird because `make docker_up` works in my M1 mac 😅 

What if you change docker-compose.yml like this:

```yaml
version: "3.7"
services:
  simulator-server:
    platform: linux/amd64 # added
    image: registry.k8s.io/scheduler-simulator/simulator-backend:v0.1.1
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-etcd:2379
      - CORS_ALLOWED_ORIGIN_LIST=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3000
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=3131
    ports:
      - "1212:1212"
      - "3131:3131"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  simulator-frontend:
    platform: linux/amd64 # added
    image: registry.k8s.io/scheduler-simulator/simulator-frontend:v0.1.1
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:1212
      - KUBE_API_SERVER_URL=http://${SIMULATOR_EXTERNAL_IP:-localhost}:3131
    ports:
    - "3000:3000"
    tty: true
  simulator-etcd:
    platform: linux/amd64 # added
    image: quay.io/coreos/etcd:v3.4.26
    container_name: simulator-etcd
    restart: always
    volumes:
      - simulator-etcd-data:/var/lib/etcd
    command: etcd --advertise-client-urls http://simulator-etcd:2379 --data-dir /var/lib/etcd --listen-client-urls http://0.0.0.0:2379 --initial-cluster-state new --initial-cluster-token tkn
    networks:
      - simulator-internal-network
volumes:
  simulator-etcd-data:
networks:
  simulator-internal-network:
    driver: bridge
```
