### ISSUE TITLE
bug: PreScore Unable to execute normally

### ISSUE THREAD

**Issue by LY-today** [kubernetes-sigs/kube-scheduler-simulator#411]
scheduler config：
```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    plugins:
      # enable the LoadAwareScheduling plugin
      preScore:
        enabled:
          - name: NodeResourcesFitPlus
        disabled:
          - name: "*"
      score:
        enabled:
          - name: NodeResourcesFitPlus
            weight: 1
        disabled:
          - name: "*"
    pluginConfig:
      # configure the thresholds and weights for the plugin
      - args:
          apiVersion: kubescheduler.config.k8s.io/v1
          kind: NodeResourcesFitPlusArgs
          resources:
            nvidia.com/gpu:
              type: MostAllocated
              weight: 2
            cpu:
              type: LeastAllocated
              weight: 1
            memory:
              type: LeastAllocated
              weight: 1
        name: NodeResourcesFitPlus
```

log：

```
2025-03-03 19:31:37 E0303 11:31:37.200393       1 run.go:74] "command failed" err="initializing profiles: creating profile for scheduler name default-scheduler: plugin \"NodeResourcesFitPlusWrapped\" does not extend PreScorePlugin plugin"
```
